version: 0.2

phases:
  install:
    commands:
      - echo "Installing Kustomize..."
      - curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
      - mv kustomize /usr/local/bin/
      - echo "Installing jq..."
      - apt-get update && apt-get install -y jq

  pre_build:
    commands:
      # These $EKS_CLUSTER_NAME, $K8S_OVERLAY, $K8S_NAMESPACE
      # variables are set in the CodePipeline configuration.
      - echo "Updating kubeconfig for cluster $EKS_CLUSTER_NAME..."
      - aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_DEFAULT_REGION
      
      - echo "Parsing image definitions..."
      # Read the image URI from the artifact passed by the CI stage
      - IMAGE_URI=$(jq -r '.[0].imageUri' imagedefinitions.json)
      - echo "Deploying image: $IMAGE_URI"
      
  build:
    commands:
      - echo "Building Kustomize manifests for overlay $K8S_OVERLAY..."
      # =====================================================================
      # THE DEPLOYMENT COMMAND:
      # 1. kustomize build...  : Generates the final YAML
      # 2. | sed ...          : Replaces the placeholder with the real image URI
      # 3. | kubectl apply... : Applies the final YAML to the cluster
      # =====================================================================
      - |
        kustomize build k8s/overlays/$K8S_OVERLAY \
        | sed "s|YOUR_IMAGE_PLACEHOLDER|$IMAGE_URI|g" \
        | kubectl apply -n $K8S_NAMESPACE -f -

  post_build:
    commands:
      - echo "Verifying deployment..."
      - |
        kubectl rollout status deployment/$(kustomize build k8s/overlays/$K8S_OVERLAY | kubectl apply -f - -n $K8S_NAMESPACE -o=jsonpath='{.metadata.name}') -n $K8S_NAMESPACE
      - echo "Deployment complete."