version: 0.2

env:
  variables:
    IMAGE_PLACEHOLDER: "YOUR_IMAGE_PLACEHOLDER"

phases:
  install:
    commands:
      # Install Kustomize directly to avoid GitHub rate-limiting
      - echo "Installing Kustomize v5.3.0..."
      - curl -s -Lo kustomize.tar.gz "https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv5.3.0/kustomize_v5.3.0_linux_amd64.tar.gz"
      - tar -xzvf kustomize.tar.gz
      - if [ -f ./kustomize ]; then mv kustomize /usr/local/bin/; else echo "Kustomize download failed!"; exit 1; fi
      
      # Install jq directly to avoid rate-limiting
      - echo "Installing jq v1.7.1..."
      - curl -s -Lo /usr/local/bin/jq "https://github.com/stedolan/jq/releases/download/jq-1.7.1/jq-linux-amd64"
      - chmod +x /usr/local/bin/jq
      - jq --version # Verify install

  pre_build:
    commands:
      - echo "Updating kubeconfig for cluster $EKS_CLUSTER_NAME..."
      - aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_DEFAULT_REGION
      - echo "Parsing image definitions..."
      - |
        # =====================================================================
        # THE FIX IS HERE:
        # We must look for the file in the BuildArtifact directory.
        # =====================================================================
        ARTIFACT_FILE="$CODEBUILD_SRC_DIR_BuildArtifact/imagedefinitions.json"

        if [ ! -f "$ARTIFACT_FILE" ]; then
          echo "Error: $ARTIFACT_FILE not found!"
          echo "This file should be an artifact from the 'Build' stage."
          ls -l $CODEBUILD_SRC_DIR_BuildArtifact
          exit 1
        fi
        
        # Safely parse the JSON file from its correct path
        IMAGE_URI=$(jq -er '.[0].imageUri' "$ARTIFACT_FILE") || {
          echo "Error: Failed to parse $ARTIFACT_FILE or .imageUri key is missing!"
          cat "$ARTIFACT_FILE"
          exit 1
        }
        
        # Export IMAGE_URI to be used in the build phase
        export IMAGE_URI
        echo "Image to deploy: $IMAGE_URI"

  build:
    commands:
      - echo "Building, validating, and applying Kustomize manifests..."
      - |
        # Build the manifest (from the primary source)
        kustomize build k8s/overlays/$K8S_OVERLAY > /tmp/kustomized.yaml
        
        # Validate that the placeholder exists before replacing
        if ! grep -q "$IMAGE_PLACEHOLDER" /tmp/kustomized.yaml; then
          echo "ERROR: Placeholder '$IMAGE_PLACEHOLDER' not found in manifest."
          echo "Check your k8s/base/deployment.yaml."
          exit 1
        fi
        
        # Replace the placeholder with the real image URI
        echo "Replacing placeholder $IMAGE_PLACEHOLDER..."
        sed -i "s|$IMAGE_PLACEHOLDER|$IMAGE_URI|g" /tmp/kustomized.yaml
        
        # Apply the final manifest
        echo "Applying manifests to namespace $K8S_NAMESPACE..."
        kubectl apply -n $K8S_NAMESPACE -f /tmp/kustomized.yaml

  post_build:
    commands:
      - |
        echo "Verifying all deployments in namespace $K8S_NAMESPACE..."
        # Loop through ALL deployments in the namespace and check their status
        for dep in $(kubectl -n $K8S_NAMESPACE get deployments -o name); do
          echo "Waiting for $dep to roll out..."
          kubectl rollout status "$dep" -n $K8S_NAMESPACE --timeout=120s
        done
        echo "All deployments complete."

